# Generated by Erlang.mk. Edit at your own risk!

src/nyam_backend_app.erl:: src/include/nyam_backend.hrl; @touch $@
src/nyam_backend_sup.erl:: src/include/nyam_backend.hrl; @touch $@

COMPILE_FIRST +=
